import {
  BarChart3,
  Bell,
  Bot,
  Building2,
  Calendar,
  Car,
  ClipboardList,
  Clock,
  Coins,
  FileCheck,
  FileText,
  Fingerprint,
  FormInput,
  GraduationCap,
  Handshake,
  Headphones,
  Key,
  Languages,
  LayoutDashboard,
  LogOut,
  Megaphone,
  MessageSquare,
  Package,
  Palmtree,
  PenTool,
  Plug,
  QrCode,
  Receipt,
  Scan,
  Settings,
  Shield,
  Smartphone,
  Sparkles,
  Timer,
  TrendingUp,
  UserPlus,
  Users,
  Wallet,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import type { StatItem } from "@/components/ui/StatGrid";
import type { FeatureItem } from "@/components/ui/FeatureGrid";

export interface ModuleRecord {
  slug: string;
  title: string;
  description: string;
  icon: LucideIcon;
  group: string;
  features: FeatureItem[];
  stats: StatItem[];
  tableTitle?: string;
  tableColumns: { key: string; label: string }[];
  tableData: Record<string, string>[];
  primaryAction?: string;
}

export type ModulePageData = Omit<ModuleRecord, "icon">;

export function toModulePageData(mod: ModuleRecord): ModulePageData {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { icon, ...data } = mod;
  return data;
}

export interface NavGroup {
  label: string;
  items: { slug: string; label: string; href: string; icon: LucideIcon }[];
}

function f(names: string[]): FeatureItem[] {
  return names.map((name) => ({ name, status: "active" as const }));
}

function tbl(rows: Record<string, string>[]) {
  return rows;
}

export const modules: Record<string, ModuleRecord> = {
  attendance: {
    slug: "attendance",
    title: "Attendance",
    description: "Attendance with GPS, WiFi, Bluetooth Beacon, Geofencing & Selfie Verification",
    icon: Clock,
    group: "Attendance & Time",
    features: f(["GPS", "WiFi Validation", "Bluetooth Beacon", "Geofencing", "Selfie Verification", "Anti Fake GPS", "Heatmap & Analytics"]),
    stats: [{ label: "Present Today", value: "187/212", color: "green" }, { label: "Late", value: 12, color: "yellow" }, { label: "Not Clocked In", value: 23, color: "red" }, { label: "Avg Attendance", value: "88%", color: "blue" }],
    tableTitle: "Today's Attendance Records",
    tableColumns: [{ key: "name", label: "Name" }, { key: "clockIn", label: "Clock In" }, { key: "location", label: "Location" }, { key: "method", label: "Method" }, { key: "status", label: "Status" }],
    tableData: tbl([{ name: "Ahmad Rizal", clockIn: "08:02", location: "HQ KL", method: "GPS + Selfie", status: "Present" }, { name: "Siti Aminah", clockIn: "08:45", location: "HQ KL", method: "WiFi", status: "Late" }, { name: "Muhammad Haziq", clockIn: "-", location: "-", method: "-", status: "Not Clocked In" }]),
    primaryAction: "View Heatmap",
  },
  shift: {
    slug: "shift",
    title: "Shift Management",
    description: "Morning, evening, night, rotational, split shift & auto roster management",
    icon: Calendar,
    group: "Attendance & Time",
    features: f(["Morning", "Evening", "Night", "Rotational", "Split Shift", "Flexible Working Hour", "Auto Roster", "Swap Shift"]),
    stats: [{ label: "Active Shifts", value: 4, color: "blue" }, { label: "Pending Swaps", value: 3, color: "yellow" }, { label: "This Week Roster", value: "100%", color: "green" }, { label: "Vacancies", value: 2, color: "red" }],
    tableTitle: "Shift Schedule",
    tableColumns: [{ key: "shift", label: "Shift" }, { key: "time", label: "Time" }, { key: "staff", label: "Staff Count" }, { key: "dept", label: "Department" }],
    tableData: tbl([{ shift: "Morning", time: "08:00 - 17:00", staff: "85", dept: "All" }, { shift: "Afternoon", time: "14:00 - 23:00", staff: "42", dept: "Operations" }, { shift: "Night", time: "22:00 - 07:00", staff: "18", dept: "Security" }]),
  },
  overtime: {
    slug: "overtime",
    title: "Overtime",
    description: "OT requests, approvals & automatic calculation",
    icon: Timer,
    group: "Attendance & Time",
    features: f(["OT Requests", "Approval", "Automatic calculation", "Weekend/Public Holiday/Night OT"]),
    stats: [{ label: "OT Today", value: 23, color: "blue" }, { label: "Pending Approval", value: 8, color: "yellow" }, { label: "OT Hours This Month", value: "342j", color: "green" }, { label: "OT Cost", value: "RM 18.4K", color: "purple" }],
    tableTitle: "OT Requests",
    tableColumns: [{ key: "name", label: "Name" }, { key: "date", label: "Date" }, { key: "hours", label: "Hours" }, { key: "type", label: "Type" }, { key: "status", label: "Status" }],
    tableData: tbl([{ name: "Faizal Rahman", date: "16 Jul", hours: "3", type: "Weekend", status: "Pending" }, { name: "Nurul Izzati", date: "15 Jul", hours: "2", type: "Night", status: "Approved" }]),
  },
  leave: {
    slug: "leave",
    title: "Leave Management",
    description: "Annual leave, medical, emergency leave & leave calendar",
    icon: Palmtree,
    group: "Attendance & Time",
    features: f(["Annual", "Medical", "Emergency", "Replacement", "Half Day", "Quarter Day", "Marriage", "Study", "Compassionate", "Leave Calendar", "Conflict Detection"]),
    stats: [{ label: "Staff on Leave", value: 14, color: "green" }, { label: "MC Today", value: 8, color: "red" }, { label: "Pending", value: 5, color: "yellow" }, { label: "Avg Balance", value: "12.4 days", color: "blue" }],
    tableTitle: "Leave Requests",
    tableColumns: [{ key: "name", label: "Name" }, { key: "type", label: "Type" }, { key: "from", label: "From" }, { key: "to", label: "To" }, { key: "status", label: "Status" }],
    tableData: tbl([{ name: "John Doe", type: "Annual", from: "20 Jul", to: "22 Jul", status: "Approved" }, { name: "Ahmad Zaki", type: "Medical", from: "17 Jul", to: "17 Jul", status: "MC" }]),
  },
  claim: {
    slug: "claim",
    title: "Claim",
    description: "Claims with receipt OCR, mileage & GST",
    icon: Receipt,
    group: "Finance",
    features: f(["OCR Receipt", "Mileage", "Auto KM calculation", "GST", "Vendor"]),
    stats: [{ label: "Claims This Month", value: 47, color: "blue" }, { label: "Pending", value: 12, color: "yellow" }, { label: "Amount", value: "RM 24.8K", color: "green" }, { label: "OCR Success", value: "94%", color: "purple" }],
    tableTitle: "Claim List",
    tableColumns: [{ key: "name", label: "Name" }, { key: "type", label: "Type" }, { key: "amount", label: "Amount" }, { key: "date", label: "Date" }, { key: "status", label: "Status" }],
    tableData: tbl([{ name: "KP KUP Shah", type: "Medical", amount: "RM 250", date: "16 Jul", status: "Pending" }, { name: "Siti Aminah", type: "Mileage", amount: "RM 85", date: "15 Jul", status: "Approved" }]),
  },
  payroll: {
    slug: "payroll",
    title: "Payroll",
    description: "Gaji, EPF, SOCSO, EIS, PCB, payslip & bank transfer",
    icon: Wallet,
    group: "Finance",
    features: f(["Basic Salary", "Allowance", "Commission", "Bonus", "OT", "Claim", "Loan", "Advance", "Deduction", "EPF", "SOCSO", "EIS", "PCB", "Payslip", "EA Form", "Bank Transfer File"]),
    stats: [{ label: "Payroll This Month", value: "RM 842K", color: "green" }, { label: "EPF", value: "RM 92.6K", color: "blue" }, { label: "PCB", value: "RM 38.2K", color: "yellow" }, { label: "Employees", value: 212, color: "purple" }],
    tableTitle: "Payroll Summary",
    tableColumns: [{ key: "name", label: "Name" }, { key: "basic", label: "Basic" }, { key: "allowance", label: "Allowance" }, { key: "deduction", label: "Deduction" }, { key: "net", label: "Net" }],
    tableData: tbl([{ name: "John Doe", basic: "RM 12,500", allowance: "RM 1,200", deduction: "RM 1,850", net: "RM 11,850" }, { name: "Ahmad Rizal", basic: "RM 9,800", allowance: "RM 800", deduction: "RM 1,420", net: "RM 9,180" }]),
  },
  "claim-approval": {
    slug: "claim-approval",
    title: "Claim Approval",
    description: "Claim approvals via approval engine",
    icon: FileCheck,
    group: "Finance",
    features: f(["Multi-level Approval", "Auto-route", "Email Notification", "Audit Trail"]),
    stats: [{ label: "Pending", value: 12, color: "yellow" }, { label: "Approved", value: 35, color: "green" }, { label: "Rejected", value: 2, color: "red" }, { label: "Avg Time", value: "1.2 days", color: "blue" }],
    tableTitle: "Pending Approvals",
    tableColumns: [{ key: "name", label: "Applicant" }, { key: "type", label: "Type" }, { key: "amount", label: "Amount" }, { key: "submitted", label: "Submitted" }],
    tableData: tbl([{ name: "KP KUP Shah", type: "Training", amount: "RM 1,200", submitted: "16 Jul" }, { name: "Muhammad Haziq", type: "Medical", amount: "RM 180", submitted: "15 Jul" }]),
    primaryAction: "Approve All",
  },
  asset: {
    slug: "asset",
    title: "Asset Management",
    description: "Laptop, phone, vehicle assets & QR/Barcode management",
    icon: Package,
    group: "People & HR",
    features: f(["Laptop", "Phone", "SIM", "Monitor", "Vehicle", "Access Card", "QR/Barcode", "Warranty", "Maintenance"]),
    stats: [{ label: "Total Assets", value: 486, color: "blue" }, { label: "Assigned", value: 412, color: "green" }, { label: "Warranty Expired", value: 18, color: "red" }, { label: "Maintenance", value: 7, color: "yellow" }],
    tableTitle: "Recent Assets",
    tableColumns: [{ key: "asset", label: "Asset" }, { key: "holder", label: "Holder" }, { key: "serial", label: "Serial" }, { key: "warranty", label: "Warranty" }],
    tableData: tbl([{ asset: "MacBook Pro 14", holder: "John Doe", serial: "MBP-2024-001", warranty: "Jun 2027" }, { asset: "iPhone 15", holder: "Ahmad Rizal", serial: "IPH-2024-042", warranty: "Mac 2026" }]),
  },
  recruitment: {
    slug: "recruitment",
    title: "Recruitment ATS",
    description: "Career portal, CV database, interview & hiring pipeline",
    icon: UserPlus,
    group: "People & HR",
    features: f(["Career Portal", "CV Database", "Interview", "Offer", "Hiring Pipeline"]),
    stats: [{ label: "Open Positions", value: 8, color: "blue" }, { label: "Active Candidates", value: 124, color: "green" }, { label: "Interview", value: 15, color: "yellow" }, { label: "Offer Pending", value: 3, color: "purple" }],
    tableTitle: "Hiring Pipeline",
    tableColumns: [{ key: "candidate", label: "Candidate" }, { key: "position", label: "Position" }, { key: "stage", label: "Stage" }, { key: "score", label: "Score" }],
    tableData: tbl([{ candidate: "Ali Rahman", position: "Software Engineer", stage: "Technical Interview", score: "85%" }, { candidate: "Priya Devi", position: "HR Executive", stage: "Offer", score: "92%" }]),
  },
  onboarding: {
    slug: "onboarding",
    title: "Onboarding",
    description: "New employee onboarding checklist",
    icon: ClipboardList,
    group: "People & HR",
    features: f(["Checklist", "Email", "Laptop", "Training", "Access Card", "Welcome Kit"]),
    stats: [{ label: "Active Onboarding", value: 4, color: "blue" }, { label: "Completed This Month", value: 6, color: "green" }, { label: "Pending Task", value: 11, color: "yellow" }, { label: "Avg Time", value: "5 days", color: "purple" }],
    tableTitle: "Checklist Onboarding",
    tableColumns: [{ key: "name", label: "Name" }, { key: "start", label: "Start Date" }, { key: "progress", label: "Progress" }, { key: "next", label: "Next Task" }],
    tableData: tbl([{ name: "Hafiz Kamal", start: "21 Jul", progress: "60%", next: "Training IT Security" }, { name: "Lisa Tan", start: "28 Jul", progress: "20%", next: "Setup Laptop" }]),
  },
  exit: {
    slug: "exit",
    title: "Exit Management",
    description: "Resignation process, clearance & exit interview",
    icon: LogOut,
    group: "People & HR",
    features: f(["Clearance", "Asset Return", "Exit Interview", "Final Salary"]),
    stats: [{ label: "Exits This Month", value: 2, color: "red" }, { label: "Clearance Pending", value: 1, color: "yellow" }, { label: "Turnover Rate", value: "5.2%", color: "blue" }, { label: "Exit Interview", value: "100%", color: "green" }],
    tableTitle: "Exit Process",
    tableColumns: [{ key: "name", label: "Name" }, { key: "lastDay", label: "Last Day" }, { key: "clearance", label: "Clearance" }, { key: "status", label: "Status" }],
    tableData: tbl([{ name: "Kevin Lim", lastDay: "31 Jul", clearance: "80%", status: "In Progress" }]),
  },
  performance: {
    slug: "performance",
    title: "Performance",
    description: "KPI, OKR, 360 review & promotion recommendations",
    icon: TrendingUp,
    group: "People & HR",
    features: f(["KPI", "OKR", "360 Review", "Promotion Recommendation"]),
    stats: [{ label: "Avg KPI", value: "87%", color: "green" }, { label: "Review Pending", value: 24, color: "yellow" }, { label: "Promotion Candidates", value: 8, color: "blue" }, { label: "Below Target", value: 12, color: "red" }],
    tableTitle: "Employee Performance",
    tableColumns: [{ key: "name", label: "Name" }, { key: "kpi", label: "KPI" }, { key: "okr", label: "OKR" }, { key: "review", label: "Review" }],
    tableData: tbl([{ name: "John Doe", kpi: "92%", okr: "4/5", review: "Excellent" }, { name: "Ahmad Rizal", kpi: "94%", okr: "5/5", review: "Excellent" }]),
  },
  training: {
    slug: "training",
    title: "Learning Management",
    description: "Video, PDF, quiz, certificates & expiry reminders",
    icon: GraduationCap,
    group: "People & HR",
    features: f(["Video", "PDF", "Quiz", "Certificate", "Expiry Reminder"]),
    stats: [{ label: "Active Courses", value: 28, color: "blue" }, { label: "Completed", value: "76%", color: "green" }, { label: "Expired", value: 9, color: "red" }, { label: "Certificates Issued", value: 156, color: "purple" }],
    tableTitle: "Training Courses",
    tableColumns: [{ key: "course", label: "Course" }, { key: "type", label: "Type" }, { key: "enrolled", label: "Participants" }, { key: "completion", label: "Completed" }],
    tableData: tbl([{ course: "IT Security Awareness", type: "Video + Quiz", enrolled: "212", completion: "89%" }, { course: "Leadership 101", type: "PDF", enrolled: "45", completion: "62%" }]),
  },
  "training-matrix": {
    slug: "training-matrix",
    title: "Training Matrix",
    description: "Mandatory training matrix & expired training",
    icon: ClipboardList,
    group: "People & HR",
    features: f(["Mandatory training", "Expired training", "Compliance Matrix", "Auto Reminder"]),
    stats: [{ label: "Mandatory Training", value: 12, color: "blue" }, { label: "Compliant", value: "94%", color: "green" }, { label: "Expired", value: 9, color: "red" }, { label: "Department", value: 8, color: "purple" }],
    tableTitle: "Training Matrix",
    tableColumns: [{ key: "training", label: "Training" }, { key: "dept", label: "Department" }, { key: "required", label: "Required" }, { key: "compliance", label: "Compliance" }],
    tableData: tbl([{ training: "Fire Safety", dept: "All", required: "Yes", compliance: "98%" }, { training: "Data Protection", dept: "IT", required: "Yes", compliance: "100%" }]),
  },
  "digital-file": {
    slug: "digital-file",
    title: "Digital Employee File",
    description: "Digital employee files with document versioning",
    icon: FileText,
    group: "Main",
    features: f(["IC", "Passport", "Certificate", "Offer Letter", "Confirmation", "Warning Letter", "Medical", "Contract", "Document Versioning"]),
    stats: [{ label: "Documents", value: "1,904", color: "blue" }, { label: "Latest Versionon", value: "98%", color: "green" }, { label: "Expired", value: 14, color: "red" }, { label: "Uploads This Month", value: 47, color: "purple" }],
    tableTitle: "Recent Documents",
    tableColumns: [{ key: "employee", label: "Employees" }, { key: "document", label: "Documents" }, { key: "version", label: "Version" }, { key: "updated", label: "Updated" }],
    tableData: tbl([{ employee: "John Doe", document: "Passport", version: "v2.9", updated: "10 Jul" }, { employee: "Ahmad Rizal", document: "Contract", version: "v3.0", updated: "01 Jul" }]),
  },
  visitor: {
    slug: "visitor",
    title: "Visitor Management",
    description: "QR pass, IC scan & visitor vehicle records",
    icon: QrCode,
    group: "Operations",
    features: f(["QR Pass", "IC Scan", "Vehicle Record", "Host Notification"]),
    stats: [{ label: "Visitors Today", value: 12, color: "blue" }, { label: "On Premises", value: 5, color: "green" }, { label: "Pre-registered", value: 8, color: "purple" }, { label: "Vehicle", value: 3, color: "yellow" }],
    tableTitle: "Visitor Log",
    tableColumns: [{ key: "name", label: "Name" }, { key: "host", label: "Host" }, { key: "checkIn", label: "Check In" }, { key: "vehicle", label: "Vehicle" }],
    tableData: tbl([{ name: "Tan Wei Ming", host: "John Doe", checkIn: "09:30", vehicle: "WBK 1234" }]),
  },
  contractor: {
    slug: "contractor",
    title: "Contractor Management",
    description: "Contractor, permit, insurance & access pass management",
    icon: Handshake,
    group: "Operations",
    features: f(["Permit", "Insurance", "Training", "Access Pass"]),
    stats: [{ label: "Active Contractors", value: 34, color: "blue" }, { label: "Permit Expired", value: 4, color: "red" }, { label: "Valid Insurance", value: "91%", color: "green" }, { label: "On-site", value: 12, color: "yellow" }],
    tableTitle: "Contractor List",
    tableColumns: [{ key: "company", label: "Company" }, { key: "permit", label: "Permit" }, { key: "insurance", label: "Insurance" }, { key: "status", label: "Status" }],
    tableData: tbl([{ company: "TechServ Sdn Bhd", permit: "Valid", insurance: "Valid", status: "Active" }]),
  },
  vehicle: {
    slug: "vehicle",
    title: "Vehicle Management",
    description: "Roadtax, insurans, servis, mileage & fuel",
    icon: Car,
    group: "Operations",
    features: f(["Roadtax", "Insurance", "Service", "Mileage", "Fuel"]),
    stats: [{ label: "Vehicle", value: 18, color: "blue" }, { label: "Roadtax Expired", value: 2, color: "red" }, { label: "Service Due", value: 3, color: "yellow" }, { label: "Fuel This Month", value: "RM 4.2K", color: "green" }],
    tableTitle: "Vehicle Fleet",
    tableColumns: [{ key: "plate", label: "Plate No." }, { key: "model", label: "Model" }, { key: "driver", label: "Driver" }, { key: "roadtax", label: "Roadtax" }],
    tableData: tbl([{ plate: "WBK 1234", model: "Toyota Hilux", driver: "Ahmad Zaki", roadtax: "Dec 2026" }]),
  },
  "meeting-room": {
    slug: "meeting-room",
    title: "Meeting Room Booking",
    description: "Meeting room, TV & projector booking",
    icon: Calendar,
    group: "Operations",
    features: f(["Booking bilik", "TV", "Projector", "Capacity"]),
    stats: [{ label: "Rooms", value: 8, color: "blue" }, { label: "Bookings Today", value: 14, color: "green" }, { label: "Available", value: 3, color: "yellow" }, { label: "Avg Utilization", value: "72%", color: "purple" }],
    tableTitle: "Today's Bookings",
    tableColumns: [{ key: "room", label: "Rooms" }, { key: "time", label: "Time" }, { key: "bookedBy", label: "Booked By" }, { key: "capacity", label: "Capacity" }],
    tableData: tbl([{ room: "Boardroom A", time: "10:00 - 11:30", bookedBy: "HR Dept", capacity: "20" }]),
  },
  helpdesk: {
    slug: "helpdesk",
    title: "Helpdesk",
    description: "IT, HR, maintenance & admin support tickets",
    icon: Headphones,
    group: "Communication",
    features: f(["IT", "HR", "Maintenance", "Admin"]),
    stats: [{ label: "Open Tickets", value: 18, color: "yellow" }, { label: "Completed Today", value: 9, color: "green" }, { label: "Avg Responsese", value: "2.4j", color: "blue" }, { label: "SLA", value: "96%", color: "purple" }],
    tableTitle: "Recent Tickets",
    tableColumns: [{ key: "ticket", label: "Ticket" }, { key: "category", label: "Category" }, { key: "subject", label: "Subject" }, { key: "status", label: "Status" }],
    tableData: tbl([{ ticket: "HD-1042", category: "IT", subject: "Laptop cannot connect to WiFi", status: "In Progress" }]),
  },
  announcement: {
    slug: "announcement",
    title: "Company Announcement",
    description: "News, policies, memos, birthdays & events",
    icon: Megaphone,
    group: "Communication",
    features: f(["News", "Policy", "Memo", "Birthday", "Events"]),
    stats: [{ label: "Active Announcements", value: 6, color: "blue" }, { label: "Read", value: "82%", color: "green" }, { label: "Events", value: 3, color: "purple" }, { label: "New Policy", value: 1, color: "yellow" }],
    tableTitle: "Recent Announcements",
    tableColumns: [{ key: "title", label: "Title" }, { key: "type", label: "Type" }, { key: "date", label: "Date" }, { key: "views", label: "Views" }],
    tableData: tbl([{ title: "Hybrid Work Policy 2026", type: "Policy", date: "15 Jul", views: "198" }, { title: "Birthday Muhammad Haziq!", type: "Birthday", date: "17 Jul", views: "156" }]),
  },
  chat: {
    slug: "chat",
    title: "Internal Chat",
    description: "Internal department chat & announcements",
    icon: MessageSquare,
    group: "Communication",
    features: f(["Department Chat", "Announcement Chat", "Direct Message", "File Sharing"]),
    stats: [{ label: "Channels", value: 12, color: "blue" }, { label: "Messages Today", value: 284, color: "green" }, { label: "Online", value: 87, color: "purple" }, { label: "Unread", value: 14, color: "yellow" }],
    tableTitle: "Active Channels",
    tableColumns: [{ key: "channel", label: "Channels" }, { key: "members", label: "Members" }, { key: "lastMsg", label: "Last Message" }, { key: "unread", label: "Unread" }],
    tableData: tbl([{ channel: "#engineering", members: "45", lastMsg: "Deploy v2.4 completed", unread: "3" }, { channel: "#hr-announcements", members: "212", lastMsg: "Hybrid policy updated", unread: "0" }]),
  },
  "form-builder": {
    slug: "form-builder",
    title: "Digital Form Builder",
    description: "Build forms without coding",
    icon: FormInput,
    group: "Automation",
    features: f(["Drag & Drop", "Conditional Logic", "Auto Route", "Template Library"]),
    stats: [{ label: "Active Forms", value: 24, color: "blue" }, { label: "Submission", value: 156, color: "green" }, { label: "Template", value: 18, color: "purple" }, { label: "Draft", value: 3, color: "yellow" }],
    tableTitle: "Digital Forms",
    tableColumns: [{ key: "form", label: "Form" }, { key: "submissions", label: "Submission" }, { key: "owner", label: "Owner" }, { key: "status", label: "Status" }],
    tableData: tbl([{ form: "Training Request", submissions: "42", owner: "HR", status: "Active" }]),
  },
  workflow: {
    slug: "workflow",
    title: "Workflow Builder",
    description: "Automation IF / THEN / ELSE",
    icon: Workflow,
    group: "Automation",
    features: f(["IF / THEN / ELSE Automation", "Trigger Events", "Email Action", "Webhook"]),
    stats: [{ label: "Active Workflows", value: 16, color: "blue" }, { label: "Runs Today", value: 89, color: "green" }, { label: "Errors", value: 1, color: "red" }, { label: "Time Saved", value: "~40h/month", color: "purple" }],
    tableTitle: "Workflow",
    tableColumns: [{ key: "name", label: "Name" }, { key: "trigger", label: "Trigger" }, { key: "runs", label: "Runs" }, { key: "status", label: "Status" }],
    tableData: tbl([{ name: "Auto-approve Leave < 1 day", trigger: "Leave Submit", runs: "23", status: "Active" }]),
  },
  approval: {
    slug: "approval",
    title: "Approval Engine",
    description: "Unlimited approval workflow",
    icon: FileCheck,
    group: "Automation",
    features: f(["Unlimited approval workflow", "Parallel Approval", "Escalation", "Delegation"]),
    stats: [{ label: "Active Flows", value: 12, color: "blue" }, { label: "Pending", value: 28, color: "yellow" }, { label: "Completed", value: 342, color: "green" }, { label: "Avg Time", value: "4.2h", color: "purple" }],
    tableTitle: "Approval Queue",
    tableColumns: [{ key: "request", label: "Request" }, { key: "requester", label: "Applicant" }, { key: "level", label: "Level" }, { key: "status", label: "Status" }],
    tableData: tbl([{ request: "Claim RM 1,200", requester: "KP KUP Shah", level: "L2", status: "Pending" }]),
  },
  "ai-ocr": {
    slug: "ai-ocr",
    title: "AI OCR",
    description: "Automatic document recognition with AI",
    icon: Scan,
    group: "AI & Analytics",
    features: f(["IC", "Passport", "Resume", "Payslip", "Receipt", "Invoice"]),
    stats: [{ label: "Documents Processed", value: "1,247", color: "blue" }, { label: "Accuracy", value: "96.8%", color: "green" }, { label: "Today", value: 34, color: "purple" }, { label: "Manual Review", value: 5, color: "yellow" }],
    tableTitle: "Log OCR",
    tableColumns: [{ key: "document", label: "Documents" }, { key: "type", label: "Type" }, { key: "accuracy", label: "Accuracy" }, { key: "time", label: "Time" }],
    tableData: tbl([{ document: "receipt_1607.pdf", type: "Receipt", accuracy: "98%", time: "2.1s" }]),
  },
  "ai-assistant": {
    slug: "ai-assistant",
    title: "AI HR Assistant",
    description: "HR queries powered by AI",
    icon: Bot,
    group: "AI & Analytics",
    features: f(["Question HR", "Policy Q&A", "Leave Balance Query", "Payroll FAQ"]),
    stats: [{ label: "Queries Today", value: 47, color: "blue" }, { label: "Auto Answered", value: "89%", color: "green" }, { label: "Avg Time", value: "1.8s", color: "purple" }, { label: "Satisfaction", value: "4.6/5", color: "yellow" }],
    tableTitle: "Recent Queries",
    tableColumns: [{ key: "question", label: "Question" }, { key: "user", label: "User" }, { key: "answer", label: "Answer" }, { key: "time", label: "Time" }],
    tableData: tbl([{ question: "What is my annual leave balance?", user: "John Doe", answer: "12 days", time: "10:32" }]),
  },
  "ai-analytics": {
    slug: "ai-analytics",
    title: "AI Analytics",
    description: "Burnout, high performer, promotion candidate & turnover",
    icon: BarChart3,
    group: "AI & Analytics",
    features: f(["Burnout", "High Performer", "Promotion Candidate", "Turnover", "Late Trend"]),
    stats: [{ label: "Burnout Risk", value: "75%", color: "red" }, { label: "High Performer", value: 18, color: "green" }, { label: "Promotion Candidates", value: 8, color: "blue" }, { label: "Turnover", value: "+5%", color: "yellow" }],
    tableTitle: "AI Insights",
    tableColumns: [{ key: "insight", label: "Insight" }, { key: "dept", label: "Department" }, { key: "severity", label: "Severity" }, { key: "action", label: "Suggestion" }],
    tableData: tbl([{ insight: "High Burnout Risk", dept: "Engineering", severity: "High", action: "Review workload" }]),
  },
  "ai-copilot": {
    slug: "ai-copilot",
    title: "AI Copilot",
    description: "Auto letters, reports, promotion suggestions & HR analysis",
    icon: Sparkles,
    group: "AI & Analytics",
    features: f(["Auto letters", "Auto reports", "Promotion suggestions", "Automatic HR analysis", "AI assistant"]),
    stats: [{ label: "Letters Generated", value: 28, color: "blue" }, { label: "Reports", value: 12, color: "green" }, { label: "Promotion Suggestions", value: 8, color: "purple" }, { label: "Chat Sessions", value: 156, color: "yellow" }],
    tableTitle: "Copilot Activity",
    tableColumns: [{ key: "action", label: "Action" }, { key: "user", label: "User" }, { key: "output", label: "Output" }, { key: "time", label: "Time" }],
    tableData: tbl([{ action: "Generate Attendance Report", user: "KP KUP Shah", output: "PDF Jul 2026", time: "09:15" }]),
    primaryAction: "Open AI Copilot",
  },
  compliance: {
    slug: "compliance",
    title: "Compliance",
    description: "ISO, audit, policy acceptance & version control",
    icon: Shield,
    group: "System",
    features: f(["ISO", "Audit", "Policy Acceptance", "Versionon Control"]),
    stats: [{ label: "Compliance Score", value: "94%", color: "green" }, { label: "Audit Pending", value: 2, color: "yellow" }, { label: "Policy Accepted", value: "97%", color: "blue" }, { label: "ISO Certs", value: 3, color: "purple" }],
    tableTitle: "Audit Trail",
    tableColumns: [{ key: "item", label: "Item" }, { key: "standard", label: "Standard" }, { key: "status", label: "Status" }, { key: "due", label: "Due" }],
    tableData: tbl([{ item: "Data Protection Policy", standard: "ISO 27001", status: "Compliant", due: "Dec 2026" }]),
  },
  "digital-signature": {
    slug: "digital-signature",
    title: "Digital Signature",
    description: "Digital signatures for offer letters, contracts & payslips",
    icon: PenTool,
    group: "System",
    features: f(["Offer Letter", "Contract", "Warning", "Payslip"]),
    stats: [{ label: "Documents Signed", value: 89, color: "green" }, { label: "Pending", value: 7, color: "yellow" }, { label: "Expired", value: 2, color: "red" }, { label: "This Month", value: 23, color: "blue" }],
    tableTitle: "Signed Documents",
    tableColumns: [{ key: "document", label: "Documents" }, { key: "signer", label: "Signer" }, { key: "status", label: "Status" }, { key: "date", label: "Date" }],
    tableData: tbl([{ document: "Offer Letter - Hafiz Kamal", signer: "HR Director", status: "Pending", date: "17 Jul" }]),
  },
  integration: {
    slug: "integration",
    title: "Integration API",
    description: "Accounting, ERP, CRM, WhatsApp & Microsoft 365 integrations",
    icon: Plug,
    group: "System",
    features: f(["Accounting", "ERP", "CRM", "Door Access", "WhatsApp", "Microsoft 365", "Google Workspace"]),
    stats: [{ label: "Active Integrations", value: 6, color: "green" }, { label: "API Calls Today", value: "12.4K", color: "blue" }, { label: "Errors", value: 3, color: "red" }, { label: "Uptime", value: "99.9%", color: "purple" }],
    tableTitle: "Integration Status",
    tableColumns: [{ key: "service", label: "Service" }, { key: "type", label: "Type" }, { key: "status", label: "Status" }, { key: "lastSync", label: "Last Sync" }],
    tableData: tbl([{ service: "Microsoft 365", type: "SSO + Calendar", status: "Connected", lastSync: "5 min ago" }, { service: "WhatsApp Business", type: "Notification", status: "Connected", lastSync: "1 min ago" }]),
  },
  mobile: {
    slug: "mobile",
    title: "Mobile App",
    description: "Mobile app for attendance, leave, claims & payslips",
    icon: Smartphone,
    group: "System",
    features: f(["Attendance", "Leave", "Claim", "Payslip", "Approval", "Notification"]),
    stats: [{ label: "Active Users", value: 198, color: "green" }, { label: "Download", value: 212, color: "blue" }, { label: "Sessions Today", value: 342, color: "purple" }, { label: "Rating", value: "4.8★", color: "yellow" }],
    tableTitle: "App Usage",
    tableColumns: [{ key: "feature", label: "Feature" }, { key: "usage", label: "Useran" }, { key: "platform", label: "Platform" }, { key: "trend", label: "Trend" }],
    tableData: tbl([{ feature: "Clock In/Out", usage: "187", platform: "iOS + Android", trend: "+12%" }]),
  },
  notification: {
    slug: "notification",
    title: "Notification Center",
    description: "Email, SMS, WhatsApp, Telegram & push notification",
    icon: Bell,
    group: "System",
    features: f(["Email", "SMS", "WhatsApp", "Telegram", "Push Notification"]),
    stats: [{ label: "Sent Today", value: 1247, color: "blue" }, { label: "Delivered", value: "98.2%", color: "green" }, { label: "Failed", value: 12, color: "red" }, { label: "Channels", value: 5, color: "purple" }],
    tableTitle: "Notification Log",
    tableColumns: [{ key: "channel", label: "Channels" }, { key: "type", label: "Type" }, { key: "sent", label: "Submitted" }, { key: "status", label: "Status" }],
    tableData: tbl([{ channel: "WhatsApp", type: "Leave Approved", sent: "45", status: "Delivered" }]),
  },
  reports: {
    slug: "reports",
    title: "Report Center",
    description: "Attendance, payroll, leave reports & Power BI export",
    icon: BarChart3,
    group: "System",
    features: f(["Attendance", "Payroll", "Leave", "Claim", "Department", "Branch", "Power BI Export"]),
    stats: [{ label: "Available Reports", value: 48, color: "blue" }, { label: "Generated This Month", value: 23, color: "green" }, { label: "Scheduled", value: 8, color: "purple" }, { label: "Export", value: 15, color: "yellow" }],
    tableTitle: "Popular Reports",
    tableColumns: [{ key: "report", label: "Reports" }, { key: "category", label: "Category" }, { key: "lastRun", label: "Last Run" }, { key: "format", label: "Format" }],
    tableData: tbl([{ report: "Monthly Attendance", category: "Attendance", lastRun: "17 Jul", format: "PDF + Excel" }]),
  },
  security: {
    slug: "security",
    title: "Security",
    description: "2FA, audit trail, IP restriction, encryption & backup",
    icon: Fingerprint,
    group: "System",
    features: f(["2FA", "Audit Trail", "IP Restriction", "Encryption", "Backup"]),
    stats: [{ label: "2FA Enabled", value: "94%", color: "green" }, { label: "Audit Events", value: "2.4K", color: "blue" }, { label: "Blocked IPs", value: 7, color: "red" }, { label: "Last Backup", value: "2h ago", color: "purple" }],
    tableTitle: "Audit Log",
    tableColumns: [{ key: "event", label: "Event" }, { key: "user", label: "User" }, { key: "ip", label: "IP" }, { key: "time", label: "Time" }],
    tableData: tbl([{ event: "Login Success", user: "KP KUP Shah", ip: "192.168.1.10", time: "08:01" }]),
  },
  "multi-company": {
    slug: "multi-company",
    title: "Multi Company",
    description: "Unlimited company, branch & department",
    icon: Building2,
    group: "System",
    features: f(["Unlimited Company", "Unlimited Branch", "Unlimited Department"]),
    stats: [{ label: "Company", value: 3, color: "blue" }, { label: "Branches", value: 12, color: "green" }, { label: "Department", value: 28, color: "purple" }, { label: "Employees", value: 212, color: "yellow" }],
    tableTitle: "Organization Structure",
    tableColumns: [{ key: "company", label: "Company" }, { key: "branch", label: "Branches" }, { key: "dept", label: "Department" }, { key: "staff", label: "Staff" }],
    tableData: tbl([{ company: "MSNC Group", branch: "HQ KL", dept: "Engineering", staff: "45" }]),
  },
  "multi-language": {
    slug: "multi-language",
    title: "Multi Language",
    description: "Language Melayu, English, 中文, தமிழ்",
    icon: Languages,
    group: "System",
    features: f(["Language Melayu", "English", "中文", "தமிழ்"]),
    stats: [{ label: "Active Languages", value: 4, color: "blue" }, { label: "Default", value: "BM", color: "green" }, { label: "Translated", value: "98%", color: "purple" }, { label: "User EN", value: "34%", color: "yellow" }],
    tableTitle: "Language",
    tableColumns: [{ key: "language", label: "Language" }, { key: "code", label: "Code" }, { key: "coverage", label: "Coverage" }, { key: "status", label: "Status" }],
    tableData: tbl([{ language: "Language Melayu", code: "ms", coverage: "100%", status: "Default" }, { language: "English", code: "en", coverage: "100%", status: "Active" }]),
  },
  "multi-currency": {
    slug: "multi-currency",
    title: "Multi Currency",
    description: "MYR, SGD, USD",
    icon: Coins,
    group: "System",
    features: f(["MYR", "SGD", "USD", "Auto Exchange Rate"]),
    stats: [{ label: "Currency", value: 3, color: "blue" }, { label: "Default", value: "MYR", color: "green" }, { label: "Rate Updated", value: "Today", color: "purple" }, { label: "Transactions", value: "RM 842K", color: "yellow" }],
    tableTitle: "Exchange Rates",
    tableColumns: [{ key: "currency", label: "Currency" }, { key: "rate", label: "Rate (vs MYR)" }, { key: "updated", label: "Updated" }],
    tableData: tbl([{ currency: "SGD", rate: "3.52", updated: "17 Jul 08:00" }, { currency: "USD", rate: "4.68", updated: "17 Jul 08:00" }]),
  },
  ess: {
    slug: "ess",
    title: "Employee Self-Service (PWA)",
    description: "Employee self-service portal — leave, claims, payslip & profile",
    icon: Users,
    group: "Additional",
    features: f(["Leave Apply", "Claim Submit", "Payslip View", "Profile Update", "Offline Mode"]),
    stats: [{ label: "ESS Users", value: 212, color: "blue" }, { label: "Active This Week", value: "89%", color: "green" }, { label: "PWA Installed", value: 156, color: "purple" }, { label: "Self-service", value: "72%", color: "yellow" }],
    tableTitle: "ESS Activity",
    tableColumns: [{ key: "action", label: "Action" }, { key: "count", label: "Count" }, { key: "period", label: "Period" }],
    tableData: tbl([{ action: "Apply Leave", count: "34", period: "This week" }]),
  },
  timesheet: {
    slug: "timesheet",
    title: "Project & Timesheet",
    description: "Project time records & timesheets",
    icon: Clock,
    group: "Additional",
    features: f(["Project Tracking", "Timesheet Entry", "Billable Hours", "Client Report"]),
    stats: [{ label: "Active Projects", value: 14, color: "blue" }, { label: "Hours This Month", value: "2,840j", color: "green" }, { label: "Billable", value: "78%", color: "purple" }, { label: "Pending", value: 6, color: "yellow" }],
    tableTitle: "Timesheet",
    tableColumns: [{ key: "project", label: "Project" }, { key: "employee", label: "Employees" }, { key: "hours", label: "Hours" }, { key: "status", label: "Status" }],
    tableData: tbl([{ project: "HRMS Phase 2", employee: "John Doe", hours: "32", status: "Submitted" }]),
  },
  "cost-center": {
    slug: "cost-center",
    title: "Cost Center & Budget",
    description: "Cost center & budget management",
    icon: Wallet,
    group: "Additional",
    features: f(["Cost Center", "Budget Allocation", "Variance Report", "Forecast"]),
    stats: [{ label: "Cost Center", value: 18, color: "blue" }, { label: "Budget", value: "RM 2.4M", color: "green" }, { label: "Used", value: "68%", color: "yellow" }, { label: "Over Budget", value: 2, color: "red" }],
    tableTitle: "Department Budget",
    tableColumns: [{ key: "dept", label: "Department" }, { key: "budget", label: "Budget" }, { key: "spent", label: "Spent" }, { key: "remaining", label: "Remaining" }],
    tableData: tbl([{ dept: "Engineering", budget: "RM 480K", spent: "RM 312K", remaining: "RM 168K" }]),
  },
  engagement: {
    slug: "engagement",
    title: "Employee Engagement",
    description: "Satisfaction surveys, pulse checks & engagement scores",
    icon: TrendingUp,
    group: "Additional",
    features: f(["Pulse Survey", "eNPS", "Feedback", "Recognition"]),
    stats: [{ label: "eNPS Score", value: 42, color: "green" }, { label: "Responsese Rate", value: "78%", color: "blue" }, { label: "Active Surveys", value: 2, color: "purple" }, { label: "Recognition", value: 34, color: "yellow" }],
    tableTitle: "Engagement",
    tableColumns: [{ key: "survey", label: "Survey" }, { key: "response", label: "Response" }, { key: "score", label: "Score" }, { key: "status", label: "Status" }],
    tableData: tbl([{ survey: "Q2 Pulse Check", response: "78%", score: "4.2/5", status: "Completed" }]),
  },
  knowledge: {
    slug: "knowledge",
    title: "Knowledge Base + AI Search",
    description: "HR knowledge base with AI search",
    icon: FileText,
    group: "Additional",
    features: f(["Article Library", "AI Search", "FAQ", "Policy Docs"]),
    stats: [{ label: "Articles", value: 156, color: "blue" }, { label: "Searches Today", value: 89, color: "green" }, { label: "AI Resolved", value: "82%", color: "purple" }, { label: "Popular", value: "Leave Policy", color: "yellow" }],
    tableTitle: "Popular Articles",
    tableColumns: [{ key: "title", label: "Title" }, { key: "category", label: "Category" }, { key: "views", label: "Views" }],
    tableData: tbl([{ title: "How to Apply Annual Leave", category: "Leave", views: "342" }]),
  },
  automation: {
    slug: "automation",
    title: "HR Automation",
    description: "Automation proses HR end-to-end",
    icon: Workflow,
    group: "Additional",
    features: f(["Onboarding Auto", "Offboarding Auto", "Reminder Auto", "Report Auto"]),
    stats: [{ label: "Active Rules", value: 24, color: "blue" }, { label: "Auto-runs Today", value: 67, color: "green" }, { label: "Time Saved", value: "~120h/month", color: "purple" }, { label: "Errors", value: 0, color: "green" }],
    tableTitle: "Automation",
    tableColumns: [{ key: "rule", label: "Rule" }, { key: "trigger", label: "Trigger" }, { key: "runs", label: "Runs" }],
    tableData: tbl([{ rule: "Birthday Email Auto", trigger: "Daily 08:00", runs: "1" }]),
  },
  saas: {
    slug: "saas",
    title: "SaaS Ready",
    description: "Multi-tenant, subscription & white-label",
    icon: Key,
    group: "Additional",
    features: f(["Multi-tenant", "Subscription", "White-label", "Usage Billing"]),
    stats: [{ label: "Tenants", value: 12, color: "blue" }, { label: "MRR", value: "RM 48K", color: "green" }, { label: "Churn", value: "2.1%", color: "yellow" }, { label: "Uptime", value: "99.95%", color: "purple" }],
    tableTitle: "SaaS Customers",
    tableColumns: [{ key: "tenant", label: "Tenant" }, { key: "plan", label: "Plan" }, { key: "users", label: "User" }, { key: "status", label: "Status" }],
    tableData: tbl([{ tenant: "ABC Corp", plan: "Enterprise", users: "250", status: "Active" }]),
  },
  settings: {
    slug: "settings",
    title: "Settings",
    description: "HRMS system configuration",
    icon: Settings,
    group: "System",
    features: f(["Company Profile", "User Roles", "Email Templates", "System Config", "Backup"]),
    stats: [{ label: "User", value: 24, color: "blue" }, { label: "Roles", value: 8, color: "green" }, { label: "Templates", value: 18, color: "purple" }, { label: "Modules", value: 46, color: "yellow" }],
    tableTitle: "Configuration",
    tableColumns: [{ key: "setting", label: "Setting" }, { key: "value", label: "Value" }, { key: "updated", label: "Updated" }],
    tableData: tbl([{ setting: "Company Name", value: "MSNC Group", updated: "01 Jul" }]),
  },
  help: {
    slug: "help",
    title: "Help & Support",
    description: "Documentation, FAQ & technical support",
    icon: Headphones,
    group: "System",
    features: f(["Documentation", "Video Tutorial", "Live Chat", "Ticket Support"]),
    stats: [{ label: "Help Articles", value: 86, color: "blue" }, { label: "Open Tickets", value: 2, color: "yellow" }, { label: "Avg Responsese", value: "< 4j", color: "green" }, { label: "Satisfaction", value: "4.7/5", color: "purple" }],
    tableTitle: "Support",
    tableColumns: [{ key: "topic", label: "Topic" }, { key: "type", label: "Type" }, { key: "status", label: "Status" }],
    tableData: tbl([{ topic: "How to Set Up GPS Attendance", type: "Guide", status: "Available" }]),
  },
};

export const navGroups: NavGroup[] = [
  {
    label: "Main",
    items: [
      { slug: "dashboard", label: "Dashboard", href: "/", icon: LayoutDashboard },
      { slug: "employee", label: "Employee 360°", href: "/employees/EMP001", icon: Users },
      { slug: "digital-file", label: "Digital File", href: "/digital-file", icon: FileText },
    ],
  },
  {
    label: "Attendance & Time",
    items: [
      { slug: "attendance", label: "Attendance", href: "/attendance", icon: Clock },
      { slug: "shift", label: "Shift", href: "/shift", icon: Calendar },
      { slug: "overtime", label: "Overtime", href: "/overtime", icon: Timer },
      { slug: "leave", label: "Leave", href: "/leave", icon: Palmtree },
    ],
  },
  {
    label: "Finance",
    items: [
      { slug: "claim", label: "Claim", href: "/claim", icon: Receipt },
      { slug: "payroll", label: "Payroll", href: "/payroll", icon: Wallet },
      { slug: "claim-approval", label: "Claim Approval", href: "/claim-approval", icon: FileCheck },
    ],
  },
  {
    label: "People & HR",
    items: [
      { slug: "asset", label: "Asset", href: "/asset", icon: Package },
      { slug: "recruitment", label: "Recruitment", href: "/recruitment", icon: UserPlus },
      { slug: "onboarding", label: "Onboarding", href: "/onboarding", icon: ClipboardList },
      { slug: "exit", label: "Exit Management", href: "/exit", icon: LogOut },
      { slug: "performance", label: "Performance", href: "/performance", icon: TrendingUp },
      { slug: "training", label: "Training", href: "/training", icon: GraduationCap },
      { slug: "training-matrix", label: "Training Matrix", href: "/training-matrix", icon: ClipboardList },
    ],
  },
  {
    label: "Operations",
    items: [
      { slug: "visitor", label: "Visitor", href: "/visitor", icon: QrCode },
      { slug: "contractor", label: "Contractor", href: "/contractor", icon: Handshake },
      { slug: "vehicle", label: "Vehicle", href: "/vehicle", icon: Car },
      { slug: "meeting-room", label: "Meeting Room", href: "/meeting-room", icon: Calendar },
    ],
  },
  {
    label: "Communication",
    items: [
      { slug: "helpdesk", label: "Helpdesk", href: "/helpdesk", icon: Headphones },
      { slug: "announcement", label: "Announcement", href: "/announcement", icon: Megaphone },
      { slug: "chat", label: "Internal Chat", href: "/chat", icon: MessageSquare },
    ],
  },
  {
    label: "Automation",
    items: [
      { slug: "form-builder", label: "Form Builder", href: "/form-builder", icon: FormInput },
      { slug: "workflow", label: "Workflow", href: "/workflow", icon: Workflow },
      { slug: "approval", label: "Approval Engine", href: "/approval", icon: FileCheck },
    ],
  },
  {
    label: "AI & Analytics",
    items: [
      { slug: "ai-ocr", label: "AI OCR", href: "/ai-ocr", icon: Scan },
      { slug: "ai-assistant", label: "AI Assistant", href: "/ai-assistant", icon: Bot },
      { slug: "ai-analytics", label: "AI Analytics", href: "/ai-analytics", icon: BarChart3 },
      { slug: "ai-copilot", label: "AI Copilot", href: "/ai-copilot", icon: Sparkles },
    ],
  },
  {
    label: "System",
    items: [
      { slug: "compliance", label: "Compliance", href: "/compliance", icon: Shield },
      { slug: "digital-signature", label: "Digital Signature", href: "/digital-signature", icon: PenTool },
      { slug: "integration", label: "Integration API", href: "/integration", icon: Plug },
      { slug: "mobile", label: "Mobile App", href: "/mobile", icon: Smartphone },
      { slug: "notification", label: "Notification", href: "/notification", icon: Bell },
      { slug: "reports", label: "Report Center", href: "/reports", icon: BarChart3 },
      { slug: "security", label: "Security", href: "/security", icon: Fingerprint },
      { slug: "multi-company", label: "Multi Company", href: "/multi-company", icon: Building2 },
      { slug: "multi-language", label: "Multi Language", href: "/multi-language", icon: Languages },
      { slug: "multi-currency", label: "Multi Currency", href: "/multi-currency", icon: Coins },
      { slug: "settings", label: "Settings", href: "/settings", icon: Settings },
      { slug: "help", label: "Help & Support", href: "/help", icon: Headphones },
    ],
  },
  {
    label: "Additional",
    items: [
      { slug: "ess", label: "ESS (PWA)", href: "/ess", icon: Users },
      { slug: "timesheet", label: "Timesheet", href: "/timesheet", icon: Clock },
      { slug: "cost-center", label: "Cost Center", href: "/cost-center", icon: Wallet },
      { slug: "engagement", label: "Engagement", href: "/engagement", icon: TrendingUp },
      { slug: "knowledge", label: "Knowledge Base", href: "/knowledge", icon: FileText },
      { slug: "automation", label: "HR Automation", href: "/automation", icon: Workflow },
      { slug: "saas", label: "SaaS Ready", href: "/saas", icon: Key },
    ],
  },
];

export function getModule(slug: string): ModuleRecord | undefined {
  return modules[slug];
}

export function getAllModuleSlugs(): string[] {
  return Object.keys(modules);
}