from pathlib import Path

REPLACEMENTS = [
    ("Kehadiran & Masa", "Attendance & Time"),
    ("Pekerja & HR", "People & HR"),
    ("AI & Analitik", "AI & Analytics"),
    ("Komunikasi", "Communication"),
    ("Automasi", "Automation"),
    ("Kewangan", "Finance"),
    ("Tambahan", "Additional"),
    ("Utama", "Main"),
    ("Hadir Hari Ini", "Present Today"),
    ("Belum Clock In", "Not Clocked In"),
    ("Purata Kehadiran", "Avg Attendance"),
    ("Rekod Kehadiran Hari Ini", "Today's Attendance Records"),
    ("Syif Aktif", "Active Shifts"),
    ("Pertukaran Pending", "Pending Swaps"),
    ("Roster Minggu Ini", "This Week Roster"),
    ("Jadual Syif", "Shift Schedule"),
    ("Bil. Staff", "Staff Count"),
    ("OT Hari Ini", "OT Today"),
    ("Pending Kelulusan", "Pending Approval"),
    ("Jam OT Bulan Ini", "OT Hours This Month"),
    ("Permohonan OT", "OT Requests"),
    ("Staff Cuti", "Staff on Leave"),
    ("MC Hari Ini", "MC Today"),
    ("Baki Purata", "Avg Balance"),
    ("12.4 hari", "12.4 days"),
    ("Permohonan Cuti", "Leave Requests"),
    ("Claim Bulan Ini", "Claims This Month"),
    ("OCR Berjaya", "OCR Success"),
    ("Senarai Tuntutan", "Claim List"),
    ("Gaji Bulan Ini", "Payroll This Month"),
    ("Ringkasan Gaji", "Payroll Summary"),
    ("Kelulusan Pending", "Pending Approvals"),
    ("Lulus Semua", "Approve All"),
    ("Jumlah Aset", "Total Assets"),
    ("Aset Terkini", "Recent Assets"),
    ("Jawatan Terbuka", "Open Positions"),
    ("Calon Aktif", "Active Candidates"),
    ("Onboarding Aktif", "Active Onboarding"),
    ("Selesai Bulan Ini", "Completed This Month"),
    ("Mula Kerja", "Start Date"),
    ("Task Seterusnya", "Next Task"),
    ("Exit Bulan Ini", "Exits This Month"),
    ("Proses Exit", "Exit Process"),
    ("Hari Terakhir", "Last Day"),
    ("KPI Purata", "Avg KPI"),
    ("Calon Promosi", "Promotion Candidates"),
    ("Prestasi Pekerja", "Employee Performance"),
    ("Kursus Aktif", "Active Courses"),
    ("Sijil Dikeluarkan", "Certificates Issued"),
    ("Kursus Latihan", "Training Courses"),
    ("Latihan Wajib", "Mandatory Training"),
    ("Matriks Latihan", "Training Matrix"),
    ("Dokumen Terkini", "Recent Documents"),
    ("Versi Terkini", "Latest Version"),
    ("Upload Bulan Ini", "Uploads This Month"),
    ("Pelawat Hari Ini", "Visitors Today"),
    ("Dalam Premis", "On Premises"),
    ("Log Pelawat", "Visitor Log"),
    ("Kontraktor Aktif", "Active Contractors"),
    ("Permit Tamat", "Permit Expired"),
    ("Insurans Valid", "Valid Insurance"),
    ("Senarai Kontraktor", "Contractor List"),
    ("Roadtax Tamat", "Roadtax Expired"),
    ("Fuel Bulan Ini", "Fuel This Month"),
    ("Fleet Kenderaan", "Vehicle Fleet"),
    ("No. Plat", "Plate No."),
    ("Booking Hari Ini", "Bookings Today"),
    ("Purata Penggunaan", "Avg Utilization"),
    ("Tempahan Hari Ini", "Today's Bookings"),
    ("Tiket Terbuka", "Open Tickets"),
    ("Selesai Hari Ini", "Completed Today"),
    ("Purata Respon", "Avg Response"),
    ("Tiket Terkini", "Recent Tickets"),
    ("Pengumuman Aktif", "Active Announcements"),
    ("Policy Baru", "New Policy"),
    ("Pengumuman Terkini", "Recent Announcements"),
    ("Mesej Hari Ini", "Messages Today"),
    ("Saluran Aktif", "Active Channels"),
    ("Mesej Terakhir", "Last Message"),
    ("Borang Aktif", "Active Forms"),
    ("Borang Digital", "Digital Forms"),
    ("Permohonan Latihan", "Training Request"),
    ("Workflow Aktif", "Active Workflows"),
    ("Jalan Hari Ini", "Runs Today"),
    ("Jimat Masa", "Time Saved"),
    ("~40j/bulan", "~40h/month"),
    ("Flow Aktif", "Active Flows"),
    ("Dokumen Diproses", "Documents Processed"),
    ("Pertanyaan Hari Ini", "Queries Today"),
    ("Dijawab Auto", "Auto Answered"),
    ("Pertanyaan Terkini", "Recent Queries"),
    ("Insight AI", "AI Insights"),
    ("Surat Dijana", "Letters Generated"),
    ("Cadangan Promosi", "Promotion Suggestions"),
    ("Sesi Chat", "Chat Sessions"),
    ("Aktiviti Copilot", "Copilot Activity"),
    ("Jana Laporan Kehadiran", "Generate Attendance Report"),
    ("Buka AI Copilot", "Open AI Copilot"),
    ("Dokumen Ditandatangani", "Documents Signed"),
    ("Dokumen Tandatangan", "Signed Documents"),
    ("Integrasi Aktif", "Active Integrations"),
    ("API Calls Hari Ini", "API Calls Today"),
    ("Status Integrasi", "Integration Status"),
    ("Sync Terakhir", "Last Sync"),
    ("5 min lalu", "5 min ago"),
    ("1 min lalu", "1 min ago"),
    ("Pengguna Aktif", "Active Users"),
    ("Sessions Hari Ini", "Sessions Today"),
    ("Penggunaan App", "App Usage"),
    ("Dihantar Hari Ini", "Sent Today"),
    ("Log Notifikasi", "Notification Log"),
    ("Laporan Tersedia", "Available Reports"),
    ("Dijana Bulan Ini", "Generated This Month"),
    ("Laporan Popular", "Popular Reports"),
    ("Kehadiran Bulanan", "Monthly Attendance"),
    ("2j lalu", "2h ago"),
    ("Struktur Organisasi", "Organization Structure"),
    ("Bahasa Aktif", "Active Languages"),
    ("Kadar Tukaran", "Exchange Rates"),
    ("Kadar (vs MYR)", "Rate (vs MYR)"),
    ("Pengguna ESS", "ESS Users"),
    ("Aktif Minggu Ini", "Active This Week"),
    ("Aktiviti ESS", "ESS Activity"),
    ("Projek Aktif", "Active Projects"),
    ("Bajet Jabatan", "Department Budget"),
    ("Survei Aktif", "Active Surveys"),
    ("Carian Hari Ini", "Searches Today"),
    ("Artikel Popular", "Popular Articles"),
    ("Rules Aktif", "Active Rules"),
    ("Auto-run Hari Ini", "Auto-runs Today"),
    ("~120j/bulan", "~120h/month"),
    ("Pelanggan SaaS", "SaaS Customers"),
    ("Artikel Bantuan", "Help Articles"),
    ("46 modul", "46 modules"),
    ("Kontrak Tamat Tempoh", "Expiring Contracts"),
    ("Lesen/Passport Tamat", "License/Passport Expiry"),
    ("Probation Tamat", "Probation Ending"),
    ("Staff Lambat", "Late Staff"),
    ("Birthday Hari Ini", "Today's Birthday"),
    ("KPI Organisasi", "Organization KPI"),
    ("Lihat Heatmap", "View Heatmap"),
    ("Ciri-ciri Modul", "Module Features"),
    ("Tambah Baru", "Add New"),
    ("Kehadiran dengan GPS, WiFi, Bluetooth Beacon, Geofencing & Selfie Verification", "Attendance with GPS, WiFi, Bluetooth Beacon, Geofencing & Selfie Verification"),
    ("Pengurusan syif pagi, petang, malam, rotational, split & auto roster", "Morning, evening, night, rotational, split shift & auto roster management"),
    ("Permohonan, kelulusan & pengiraan OT automatik", "OT requests, approvals & automatic calculation"),
    ("Pengurusan cuti tahunan, MC, kecemasan & kalendar cuti", "Annual leave, medical, emergency leave & leave calendar"),
    ("Tuntutan dengan OCR resit, mileage & GST", "Claims with receipt OCR, mileage & GST"),
    ("Kelulusan tuntutan melalui approval engine", "Claim approvals via approval engine"),
    ("Pengurusan aset laptop, telefon, kenderaan & QR/Barcode", "Laptop, phone, vehicle assets & QR/Barcode management"),
    ("Checklist onboarding pekerja baharu", "New employee onboarding checklist"),
    ("Proses peletakan jawatan, clearance & exit interview", "Resignation process, clearance & exit interview"),
    ("KPI, OKR, 360 Review & cadangan kenaikan pangkat", "KPI, OKR, 360 review & promotion recommendations"),
    ("Video, PDF, quiz, sijil & peringatan tamat tempoh", "Video, PDF, quiz, certificates & expiry reminders"),
    ("Matriks latihan wajib & latihan tamat tempoh", "Mandatory training matrix & expired training"),
    ("Fail digital pekerja dengan versioning dokumen", "Digital employee files with document versioning"),
    ("QR Pass, IC scan & rekod kenderaan pelawat", "QR pass, IC scan & visitor vehicle records"),
    ("Pengurusan kontraktor, permit, insurans & access pass", "Contractor, permit, insurance & access pass management"),
    ("Tempahan bilik mesyuarat, TV & projector", "Meeting room, TV & projector booking"),
    ("Tiket sokongan IT, HR, Maintenance & Admin", "IT, HR, maintenance & admin support tickets"),
    ("Berita, polisi, memo, birthday & events", "News, policies, memos, birthdays & events"),
    ("Chat dalaman jabatan & pengumuman", "Internal department chat & announcements"),
    ("Bina borang tanpa coding", "Build forms without coding"),
    ("Pengecaman dokumen automatik dengan AI", "Automatic document recognition with AI"),
    ("Pertanyaan HR menggunakan AI", "HR queries powered by AI"),
    ("Auto surat, laporan, cadangan kenaikan pangkat & analisis HR", "Auto letters, reports, promotion suggestions & HR analysis"),
    ("Tandatangan digital untuk offer letter, contract & payslip", "Digital signatures for offer letters, contracts & payslips"),
    ("Integrasi Accounting, ERP, CRM, WhatsApp & Microsoft 365", "Accounting, ERP, CRM, WhatsApp & Microsoft 365 integrations"),
    ("Aplikasi mudah alih untuk attendance, leave, claim & payslip", "Mobile app for attendance, leave, claims & payslips"),
    ("Laporan attendance, payroll, leave & Power BI export", "Attendance, payroll, leave reports & Power BI export"),
    ("Portal pekerja sendiri — cuti, claim, payslip & profil", "Employee self-service portal — leave, claims, payslip & profile"),
    ("Rekod masa projek & timesheet", "Project time records & timesheets"),
    ("Pengurusan cost center & bajet", "Cost center & budget management"),
    ("Survei kepuasan, pulse check & engagement score", "Satisfaction surveys, pulse checks & engagement scores"),
    ("Pangkalan pengetahuan HR dengan carian AI", "HR knowledge base with AI search"),
    ("Automasi proses HR end-to-end", "End-to-end HR process automation"),
    ("Konfigurasi sistem HRMS", "HRMS system configuration"),
    ("Dokumentasi, FAQ & sokongan teknikal", "Documentation, FAQ & technical support"),
    ("Lambat", "Late"),
    ("Lokasi", "Location"),
    ("Kaedah", "Method"),
    ("Hadir", "Present"),
    ("Kekosongan", "Vacancies"),
    ("Syif", "Shift"),
    ("Masa", "Time"),
    ("Jabatan", "Department"),
    ("Pagi", "Morning"),
    ("Petang", "Afternoon"),
    ("Malam", "Night"),
    ("Tarikh", "Date"),
    ("Jam", "Hours"),
    ("Jenis", "Type"),
    ("Dari", "From"),
    ("Hingga", "To"),
    ("Jumlah", "Amount"),
    ("Pekerja", "Employees"),
    ("Asas", "Basic"),
    ("Elaun", "Allowance"),
    ("Potongan", "Deduction"),
    ("Bersih", "Net"),
    ("Diluluskan", "Approved"),
    ("Purata Masa", "Avg Time"),
    ("1.2 hari", "1.2 days"),
    ("Pemohon", "Applicant"),
    ("Dihantar", "Submitted"),
    ("Diassign", "Assigned"),
    ("Warranty Tamat", "Warranty Expired"),
    ("Aset", "Asset"),
    ("Pemegang", "Holder"),
    ("Calon", "Candidate"),
    ("Jawatan", "Position"),
    ("Peringkat", "Stage"),
    ("Skor", "Score"),
    ("5 hari", "5 days"),
    ("Ditolak", "Rejected"),
    ("Dalam Proses", "In Progress"),
    ("Cemerlang", "Excellent"),
    ("Selesai", "Completed"),
    ("Tamat Tempoh", "Expired"),
    ("Kursus", "Course"),
    ("Peserta", "Participants"),
    ("Latihan", "Training"),
    ("Wajib", "Required"),
    ("Latihan wajib", "Mandatory training"),
    ("Latihan tamat tempoh", "Expired training"),
    ("Dokumen", "Documents"),
    ("Versi", "Version"),
    ("Kemaskini", "Updated"),
    ("Kenderaan", "Vehicle"),
    ("Syarikat", "Company"),
    ("Insurans", "Insurance"),
    ("Aktif", "Active"),
    ("Servis Due", "Service Due"),
    ("Pemandu", "Driver"),
    ("Bilik", "Rooms"),
    ("Tersedia", "Available"),
    ("Ditempah", "Booked By"),
    ("Kapasiti", "Capacity"),
    ("Tiket", "Ticket"),
    ("Kategori", "Category"),
    ("Subjek", "Subject"),
    ("Laptop tidak connect WiFi", "Laptop cannot connect to WiFi"),
    ("Dibaca", "Read"),
    ("Tajuk", "Title"),
    ("Baca", "Views"),
    ("Saluran", "Channels"),
    ("Ahli", "Members"),
    ("Borang", "Form"),
    ("Pemilik", "Owner"),
    ("Ralat", "Errors"),
    ("4.2j", "4.2h"),
    ("Permintaan", "Request"),
    ("Ketepatan", "Accuracy"),
    ("Hari Ini", "Today"),
    ("Pertanyaan", "Question"),
    ("Pengguna", "User"),
    ("Jawapan", "Answer"),
    ("Cadangan", "Suggestion"),
    ("Tindakan", "Action"),
    ("Laporan", "Reports"),
    ("Bulan Ini", "This Month"),
    ("Penandatangan", "Signer"),
    ("Perkhidmatan", "Service"),
    ("Penggunaan", "Usage"),
    ("Dihantar", "Sent"),
    ("Terakhir", "Last Run"),
    ("Cawangan", "Branches"),
    ("Bahasa", "Language"),
    ("Kod", "Code"),
    ("Mata Wang", "Currency"),
    ("Bilangan", "Count"),
    ("Tempoh", "Period"),
    ("Minggu ini", "This week"),
    ("Projek", "Project"),
    ("Bajet", "Budget"),
    ("Digunakan", "Spent"),
    ("Baki", "Remaining"),
    ("Survei", "Survey"),
    ("Respon", "Response"),
    ("Artikel", "Articles"),
    ("Konfigurasi", "Configuration"),
    ("Nilai", "Value"),
    ("Sokongan", "Support"),
    ("Topik", "Topic"),
    ("Nama", "Name"),
    ("Dis 2026", "Dec 2026"),
    ("Kontrak Tamat", "Contract Expiry"),
    ("Kos OT", "OT Cost"),
    ("Kepuasan", "Satisfaction"),
    ("Burnout Risk Tinggi", "High Burnout Risk"),
    ("Tinggi", "High"),
    ("Semak beban kerja", "Review workload"),
    ("Auto surat", "Auto letters"),
    ("Auto laporan", "Auto reports"),
    ("Cadangan kenaikan pangkat", "Promotion suggestions"),
    ("Analisis HR automatic", "Automatic HR analysis"),
    ("Permohonan OT", "OT Request"),
    ("Kelulusan", "Approval"),
    ("Pengiraan automatik", "Automatic calculation"),
    ("Auto kira KM", "Auto KM calculation"),
    ("Lihat", "View"),
    ("Lulus", "Approve"),
    ("Polisi Kerja Hybrid 2026", "Hybrid Work Policy 2026"),
    ("Deploy v2.4 selesai", "Deploy v2.4 completed"),
    ("Polisi hybrid dikemaskini", "Hybrid policy updated"),
    ("Baki cuti tahunan saya?", "What is my annual leave balance?"),
    ("12 hari", "12 days"),
    ("Cara Mohon Cuti Tahunan", "How to Apply Annual Leave"),
    ("Cara setup GPS Attendance", "How to Set Up GPS Attendance"),
    ("Tersedia", "Available"),
    ("Auto-approve Leave < 1 hari", "Auto-approve Leave < 1 day"),
    ("+5% bulan ini", "+5% this month"),
]

def translate_file(path: Path):
    text = path.read_text(encoding="utf-8")
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    path.write_text(text, encoding="utf-8")
    print(f"Translated: {path}")

if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    translate_file(root / "src" / "lib" / "modules.ts")